name: VeloAdminBridge
version: '1.3.0'
main: fr.veloadmin.bridge.VeloAdminBridgePlugin
api-version: '1.21'
author: herocraftlol
description: Bridge cote serveur pour VeloAdmin (vanish + teleportation reelle)

commands:
  list:
    description: Liste les joueurs en ligne (filtre les joueurs en vanish)

permissions:
  veloadmin.vanish.see:
    description: Peut voir les joueurs en vanish
    default: op
